### PR TITLE
fix: circular import

### LINKED ISSUE #1226: Circular import triggered by the EnsemblePlotAdapterWrapper import in training/train/methods/ensemble.py
### What happened?

 utils.checkpoint imports BaseTrainingModule/training methods -> train/methods/__init__.py imports ensemble.py -> ensemble.py imports diagnostics callbacks via EnsemblePlotAdapterWrapper -> diagnostics callbacks import AnemoiCheckpoint -> AnemoiCheckpoint imports check_classes back from utils.checkpoint

ImportError: cannot import name 'check_classes' from partially initialized module 'anemoi.training.utils.checkpoint'

### What are the steps to reproduce the bug?

anemoi-training checkpoint inference ... 

### Version

92ddccf49

### Platform (OS and architecture)

any

### Relevant log output

```shell

```

### Accompanying data

_No response_

### Organisation

_No response_

### PR DESCRIPTION
**Pull request by VeraChristina**
## Description
Fixes the circular import introduced in https://github.com/ecmwf/anemoi-core/commit/92ddccf49c67e1e3e0bbf4e56898bcd50086755c

## What issue or task does this change relate to?
Closes https://github.com/ecmwf/anemoi-core/issues/1226

##  Additional notes ##

***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a parallel setting  (i.e., with multiple GPUs). As a reviewer, you are also responsible for verifying these aspects and requesting changes if they are not adequately addressed. For guidelines about those please refer to https://anemoi.readthedocs.io/en/latest/***

By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/Contributor-License-Agreement.md)

### CODE REVIEW

**Review by mchantry — APPROVED** [review]
LGTM, thanks.
